### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by ramirous** [bow/abifpy#4]
Hello,
I'm new in bioinformatics, but I followed your instructions to install the program and got this error:

> > > from abifpy import Trace
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in ?
> > >   File "abifpy.py", line 18
> > >     **version** += '-dev' if not RELEASE else ''
> > >                                        ^
> > > SyntaxError: invalid syntax

Any ideas?

Cheers.

**Comment by bow** [comment]
Closing because of inactivity.
